### ISSUE TITLE
Very old mouse format, incompatible with some streaming services

### ISSUE THREAD

**Issue by cbartondock** [ArcticaProject/vcxsrv#14]
Hi,

My issue is a weird one. I use Parsec as a remote desktop service as opposed to Microsoft Remote Desktop, for various reasons, and I've noticed that while vcxsrv works well it has graphical issues involving the cursor when using Parsec. Namely, there is a black box around the cursor. The reason is that they don't support the mouse format you're using (xbitmap I take it, which was mostly retired in 1989). I've already asked them if they plan on supporting it, and they said they do eventually but it's so old/rare that it's hardly an issue (this was their discord so they were actually honest about that). Is there anyway you could switch over to a more modern format for mouse icons?

**Comment by uli42** [comment]
On Fri, Mar 8, 2019 at 5:35 AM Chris Dock <notifications@github.com> wrote:
> My issue is a weird one. I use Parsec as a remote desktop service as opposed to Microsoft Remote Desktop, for various reasons, and I've noticed that while vcxsrv works well it has graphical issues involving the cursor when using Parsec. Namely, there is a black box around the cursor. The reason is that they don't support the mouse format you're using (xbitmap I take it, which was mostly retired in 1989). I've already asked them if they plan on supporting it, and they said they do eventually but it's so old/rare that it's hardly an issue (this was their discord so they were actually honest about that). Is there anyway you could switch over to a more modern format for mouse icons?

Vcxsrv 1.20.0.0 has been included from x2go 4.1.2.0 (released
2018-06-25). X2go is now shipping the upstream version so this repo is
no longer maintained.So this is probably a bug that affects VcXsrv
upstream. Please try the current version from there (1.20.1.4) and
open a bug there:

However: can you please add more details? I doubt that vcxsrv only
supports format that was retired in 1989 as the code is based on the
most current Xorg code from 2019 and should support everything a
modern X server offfers.

Uli

**Comment by cbartondock** [comment]
Problem seems to have been fixed in more recent versions.
