### ISSUE TITLE
"another window manager is running" but it's not

### ISSUE THREAD

**Issue by gpion** [ArcticaProject/vcxsrv#22]
Hello,

I'm getting sometimes this error in the log :

```
winClipboardProc - xcb_connect () returned and successfully opened the display.
winMultiWindowXMsgProc - another window manager is running.  Exiting.
Using Composite redirection
winMultiWindowWMProc - Error code: 8 (Match), ID: 0x00280000, Major opcode: 12 (ConfigureWindow), Minor opcode: 0 ((null))
(EE) Server terminated with error (1). Closing log file.
```

according to [tcpview](https://learn.microsoft.com/fr-fr/sysinternals/downloads/tcpview), TCP port 6000 is closed and no other vcxsrv process is running

Version info : 
Release: 21.1.10.0
OS: Windows NT 6.2 build 9200 (64-bit)

**Comment by uli42** [comment]
Sometimes vcxsrv crashes and seemingly leaves some resources open. It might
help to wait some time, then retry.

Uli

Btw: iirc this repo is not the current one for vcxsrv. X2go comes with a
current version. And I think that is unaltered from the upstream version at
sourceforge.

gpion ***@***.***> schrieb am Fr., 15. März 2024, 09:50:

**Comment by gpion** [comment]
> Btw: iirc this repo is not the current one for vcxsrv. X2go comes with a current version

Oh sorry!
Do you have the url of the official vcxsrv repository ?

**Comment by gpion** [comment]
> Do you have the url of the official vcxsrv repository ?

Found it : https://github.com/marchaesen/vcxsrv
( but it seems there is not much activity there)
